modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="equestria_delight"
version="1.0.0"
displayName="Equestria Delight"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MiniTiff, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.equestria_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration